CREATE TABLE IF NOT EXISTS zhihudata(
		Id INT NOT NULL,
		Gaprefix VARCHAR(200) NOT NULL,
		Thumbnail VARCHAR(200) NOT NULL,
		Shareurl VARCHAR(200) NOT NULL,
		Image VARCHAR(200) NOT NULL,
		Url VARCHAR(200) NOT NULL,
		Title TEXT NOT NULL,
		Date CHAR(8) NOT NULL
)